### ISSUE TITLE
возврат на базу

### ISSUE THREAD

**Issue by AlexKash500** [AlexxIT/VacuumZones#1]
Не правильно работает команда через Станцию "Верни пылесос на базу". Если выбрать больше одной комнаты, то эта команда сначала ставит пылесос на паузу, при повторе запускает уборку следующей комнаты и т.д.

**Comment by AlexxIT** [comment]
Так и задумано. Верни на базу пропускает текущую комнату. А останови уборку принудительно завершает все задачи и возвращает пылесос на базу

**Comment by p1ne** [comment]
при этом "выключи робот пылесос" срабатывает как "верни на базу". Логичнее наверное все же завершать в этом случае все задачи и вернуть на базу. Еще было бы хорошо иметь возможность видеть в HA текущую очередь на уборку

**Comment by AlexxIT** [comment]
Это вопрос к Яндексу, какие фразы они привязали к командам. Очередь уборки можно увидеть, если добавить в карточку entities все свои пылесосы. Только последовательность уборки не будет понятна.
