### ISSUE TITLE
Using deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by avbor** [AlexxIT/VacuumZones#11]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1567
First occurred: 16:27:05 (7 occurrences)
Last logged: 16:27:07

Entity vacuum.kukhnia (<class 'custom_components.vacuum_zones.vacuum.XiaomiVacuum'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <VacuumEntityFeature.STOP|START: 8200>, please report it to the author of the 'vacuum_zones' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by avbor** [comment]
++
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:948
First occurred: 19:11:50 (1 occurrences)
Last logged: 19:11:50

Entity vacuum.gostinaia (<class 'custom_components.vacuum_zones.vacuum.XiaomiVacuum'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the author of the 'vacuum_zones' custom integration
```

**Comment by Mark612** [comment]
WARNING:homeassistant.helpers.typing:HomeAssistantType was used from vacuum_zones, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'vacuum_zones' custom integration

**Comment by Mark612** [comment]
Are these deprecated alias' being updated, or do we need to look for alternate solutions?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/VacuumZones/releases/tag/v1.1.0

**Comment by Mark612** [comment]
Still getting the error with 1.1.0

2025-05-04 18:16:42.229 WARNING (ImportExecutor_0) [homeassistant.components.vacu
um] STATE_CLEANING was used from vacuum_zones, this is a deprecated constant whic
h will be removed in HA Core 2026.1. Use VacuumActivity.CLEANING instead, please
report it to the author of the 'vacuum_zones' custom integration
2025-05-04 18:16:42.234 WARNING (ImportExecutor_0) [homeassistant.components.vacu
um] STATE_RETURNING was used from vacuum_zones, this is a deprecated constant whi
ch will be removed in HA Core 2026.1. Use VacuumActivity.RETURNING instead, pleas
e report it to the author of the 'vacuum_zones' custom integration
2025-05-04 18:16:42.237 WARNING (ImportExecutor_0) [homeassistant.components.vacu
um] STATE_DOCKED was used from vacuum_zones, this is a deprecated constant which
will be removed in HA Core 2026.1. Use VacuumActivity.DOCKED instead, please repo
rt it to the author of the 'vacuum_zones' custom integration
