### ISSUE TITLE
Is it possible to add it to a Custom Card in a Custom Dashboard?

### ISSUE THREAD

**Issue by diegofrances** [AlexxIT/VacuumZones#13]
Hello @AlexxIT ,

Sorry to bug you directly but I have tried and I have failed to add your solution to a Custom Card on a Custom Dashboard.

Can you please explain how to create a Custom Card on a Custom Dashboard?

Thank you in advance.

**Comment by AlexxIT** [comment]
I don't understand your question. This component not related to any custom card/dashboard.
