### ISSUE TITLE
service error

### ISSUE THREAD

**Issue by ahtoh1029** [AlexxIT/VacuumZones#4]
zone clean failed with log message in homeassistant

homeassistant.exceptions.ServiceNotFound: Unable to find service xiaomi_miio.vacuum_clean_segment

**Comment by WooDeNDark** [comment]
Same issue

**Comment by AlexxIT** [comment]
What vacuum model you using?

**Comment by ahtoh1029** [comment]
roborock t7 pro( china version of s6 maxv)

**Comment by AlexxIT** [comment]
What `xiaomi_miio` service do you have? You can check them in developer tools

**Comment by ahtoh1029** [comment]
> What `xiaomi_miio` service do you have? You can check them in developer tools

in the beginning i integrated t7 pro via miio, weeks ago it went unavailable so i was forced to integrate t7 pro via miot. then i found there is no vacuum relative service in miio services list and miot list any more. i'm using the genuine vacuum services of homeassistant to do basic operation now.

**Comment by AlexxIT** [comment]
So you can use `sequence:` call with this integration.

**Comment by ahtoh1029** [comment]
> So you can use `sequence:` call with this integration.

   Entryway:  # zone name on your language
      sequence:  # optional script sequence (run before command to vacuum)
      - service: vacuum.start
        target:
          entity_id: vacuum.a09_cloud_887867
      room: 22


tried this, it will clean the whole house, not the assigned zone

**Comment by basirmuhamedkulov** [comment]
> What `xiaomi_miio` service do you have? You can check them in developer tools

Same issue
Vacuum Lydsto W2 zhimi.vacuum.w2, added via [Xiaomi Miot Auto](urlhttps://github.com/al-one/hass-xiaomi-miot)
There is no xiaomi_miio.vacuum_clean_segment in dev tools

**Comment by AlexxIT** [comment]
Please reopen the issue if there are still any problems
